{
 "title": "DNS Mesh Sidecar Metrics Dasboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Overall Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Number of Policies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "informal_metrics{protocol=\"number_of_policies\",type=\"policy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dns Controller Policy Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "rate(dns_errors_total{sidecar_metrics=\"dns\", type=\"policy_fetch\", protocol=\"policy_upstream\"}[5m])",
     "legendFormat": "{{type}}_error"
    },
    {
     "expr": "rate(dns_errors_total{sidecar_metrics=\"dns\", type=\"policy_fetch\", protocol=\"policy_upstream_http_err\"}[5m])",
     "legendFormat": "{{protocol}}_error"
    },
    {
     "expr": "rate(dns_errors_total{sidecar_metrics=\"dns\", type=\"policy_fetch\", protocol=\"policy_upstream_decode_err\"}[5m])",
     "legendFormat": "{{protocol}}_error"
    }
   ]
  },
  {
   "title": "Blocking DNS Queries by Protocol",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(dns_query_duration_seconds_count{protocol=\"udp\"}[5m])",
     "legendFormat": "{{protocol}}_{{status}}"
    },
    {
     "expr": "rate(dns_query_duration_seconds_count{protocol=\"tcp\"}[5m])",
     "legendFormat": "{{protocol}}_{{status}}"
    }
   ]
  },
  { "title": "Error Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Sidecar DNS Client Write Errors",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(dns_errors_total{sidecar_metrics=\"dns\", type=\"client_write\", protocol=\"udp\"}[5m])",
     "legendFormat": "{{type}}_error"
    }
   ]
  },
  {
   "title": "Sidecar DNS Client Write Errors",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 7 },
   "targets": [
    {
     "expr": "rate(dns_errors_total{sidecar_metrics=\"dns\", type=\"client_write\", protocol=\"udp\"}[5m])",
     "legendFormat": "{{type}}_error"
    }
   ]
  },
  {
   "title": "Upstream Timeout Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 7 },
   "targets": [
    {
     "expr": "rate(dns_errors_total{sidecar_metrics=\"dns\", type=\"upstream_timeout\", protocol=\"udp\"}[5m])",
     "legendFormat": "{{protocol}}_{{type}}"
    },
    {
     "expr": "rate(dns_errors_total{sidecar_metrics=\"dns\", type=\"upstream_timeout\", protocol=\"tcp\"}[5m])",
     "legendFormat": "{{protocol}}_{{type}}"
    }
   ]
  },
  {
   "title": "Upstream Read Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "rate(dns_errors_total{sidecar_metrics=\"dns\", type=\"upstream_read\", protocol=\"udp\"}[5m])",
     "legendFormat": "{{protocol}}_{{type}}"
    },
    {
     "expr": "rate(dns_errors_total{sidecar_metrics=\"dns\", type=\"upstream_read\", protocol=\"tcp\"}[5m])",
     "legendFormat": "{{protocol}}_{{type}}"
    }
   ]
  },
  {
   "title": "Upstream Write Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(dns_errors_total{sidecar_metrics=\"dns\", type=\"upstream_write\", protocol=\"udp\"}[5m])",
     "legendFormat": "{{type}}_{{status}}"
    },
    {
     "expr": "rate(dns_errors_total{sidecar_metrics=\"dns\", type=\"upstream_write\", protocol=\"tcp\"}[5m])",
     "legendFormat": "{{type}}_{{status}}"
    }
   ]
  },
  {
   "title": "Upstream Dial Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 7, "y": 11 },
   "targets": [
    {
     "expr": "rate(dns_errors_total{sidecar_metrics=\"dns\", type=\"upstream_dial\", protocol=\"udp\"}[5m])",
     "legendFormat": "{{type}}_{{status}}"
    },
    {
     "expr": "rate(dns_errors_total{sidecar_metrics=\"dns\", type=\"upstream_dial\", protocol=\"tcp\"}[5m])",
     "legendFormat": "{{type}}_{{status}}"
    }
   ]
  },
  {
   "title": "DNS Parse Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "rate(dns_errors_total{sidecar_metrics=\"dns\", type=\"parse\", protocol=\"udp\"}[5m])",
     "legendFormat": "{{type}}_{{status}}"
    },
    {
     "expr": "rate(dns_errors_total{sidecar_metrics=\"dns\", type=\"parse\", protocol=\"tcp\"}[5m])",
     "legendFormat": "{{type}}_{{status}}"
    }
   ]
  }
 ]
}